/// Build canonical unified editions under `db/unified/`.
///
/// Spine = AhmedBaset `db/by_book` (structure + Arabic + English narrator/text).
/// Enrich grades/reference from spine (muallimai) and fawaz `grades[]`.
/// Join non-English translations from fawaz `db/editions/files/{lang}-{book}.min.json`
/// by `idInBook == hadithnumber` (fallback `arabicnumber`).
/// Indonesian drafts from sagad for spine-only books.
///
/// Usage: `dart run tool/build_unified_editions.dart`
library;

import 'dart:convert';
import 'dart:io';

const _schemaVersion = 1;

/// Spine file basename → unified bookKey / bookId / optional fawaz book key.
const _books = <_BookDef>[
  _BookDef('bukhari', 1, 'the_9_books/bukhari.json', fawazKey: 'bukhari'),
  _BookDef('muslim', 2, 'the_9_books/muslim.json', fawazKey: 'muslim'),
  _BookDef('nasai', 3, 'the_9_books/nasai.json', fawazKey: 'nasai'),
  _BookDef('abudawud', 4, 'the_9_books/abudawud.json', fawazKey: 'abudawud'),
  _BookDef('tirmidhi', 5, 'the_9_books/tirmidhi.json', fawazKey: 'tirmidhi'),
  _BookDef('ibnmajah', 6, 'the_9_books/ibnmajah.json', fawazKey: 'ibnmajah'),
  _BookDef('malik', 7, 'the_9_books/malik.json', fawazKey: 'malik'),
  _BookDef('ahmad', 8, 'the_9_books/ahmed.json'),
  _BookDef('darimi', 9, 'the_9_books/darimi.json'),
  _BookDef('nawawi', 10, 'forties/nawawi40.json', fawazKey: 'nawawi'),
  _BookDef('qudsi', 11, 'forties/qudsi40.json', fawazKey: 'qudsi'),
  _BookDef('dehlawi', 12, 'forties/shahwaliullah40.json', fawazKey: 'dehlawi'),
  _BookDef('riyad', 13, 'other_books/riyad_assalihin.json'),
  _BookDef('mishkat', 14, 'other_books/mishkat_almasabih.json'),
  _BookDef('adab', 15, 'other_books/aladab_almufrad.json'),
  _BookDef('shamail', 16, 'other_books/shamail_muhammadiyah.json'),
  _BookDef('bulugh', 17, 'other_books/bulugh_almaram.json'),
  _BookDef('hisn', 18, 'other_books/hisn_almuslim.json'),
];

/// Fawaz filename lang prefix → unified language code + display name.
const _langDefs = <String, _LangDef>{
  'ara': _LangDef('ar', 'Arabic', 'ara'),
  'ara1': _LangDef('ar-undiacritized', 'Arabic (undiacritized)', 'ara1'),
  'eng': _LangDef('en', 'English', 'eng'),
  'ben': _LangDef('bn', 'Bengali', 'ben'),
  'fra': _LangDef('fr', 'French', 'fra'),
  'ind': _LangDef('id', 'Indonesian', 'ind'),
  'rus': _LangDef('ru', 'Russian', 'rus'),
  'tam': _LangDef('ta', 'Tamil', 'tam'),
  'tur': _LangDef('tr', 'Turkish', 'tur'),
  'urd': _LangDef('ur', 'Urdu', 'urd'),
};

final _pretty = const JsonEncoder.withIndent('\t');
final _min = const JsonEncoder();

void main(List<String> args) {
  final root = Directory(args.isNotEmpty ? args.first : '.');
  final db = Directory('${root.path}${Platform.pathSeparator}db');
  final unified = Directory('${db.path}${Platform.pathSeparator}unified');
  final filesDir =
      Directory('${unified.path}${Platform.pathSeparator}files');
  final byBookDir =
      Directory('${unified.path}${Platform.pathSeparator}by_book');
  if (unified.existsSync()) {
    unified.deleteSync(recursive: true);
  }
  filesDir.createSync(recursive: true);
  byBookDir.createSync(recursive: true);

  final report = StringBuffer()
    ..writeln('# Unified editions build report')
    ..writeln()
    ..writeln('Generated by `tool/build_unified_editions.dart`.')
    ..writeln()
    ..writeln('## Discarded fawaz edition duplicates')
    ..writeln()
    ..writeln(
      'Primary editions only (`{lang}-{book}` / `ara1-{book}`). '
      'No alternate English variants were present in `db/editions/files` at build time.',
    )
    ..writeln()
    ..writeln('## Fawaz ↔ spine match rates')
    ..writeln()
    ..writeln(
      '| Book | Lang | Fawaz rows | Matched (hadithnumber) | Matched (arabicnumber) | Unmatched (skipped) | Spine hadiths |',
    )
    ..writeln('|---|---|---:|---:|---:|---:|---:|');

  final notes = <String>[];
  final catalogEditions = <Map<String, dynamic>>[];
  final matrix = <String, Set<String>>{};

  for (final book in _books) {
    stdout.writeln('Building ${book.key}...');
    final spineFile = File(
      '${db.path}${Platform.pathSeparator}by_book${Platform.pathSeparator}'
      '${book.spineRel.replaceAll('/', Platform.pathSeparator)}',
    );
    if (!spineFile.existsSync()) {
      stderr.writeln('Missing spine: ${spineFile.path}');
      continue;
    }
    final spine =
        jsonDecode(spineFile.readAsStringSync()) as Map<String, dynamic>;
    final spineMeta = spine['metadata'] as Map<String, dynamic>? ?? {};
    final chapters = _normalizeChapters(spine['chapters'] as List? ?? const []);
    final spineHadiths = (spine['hadiths'] as List? ?? const [])
        .map((e) => Map<String, dynamic>.from(e as Map))
        .toList();

    // Index by idInBook (and assign synthetic idInBook for hisn-like gaps).
    final byIdInBook = <int, Map<String, dynamic>>{};
    for (var i = 0; i < spineHadiths.length; i++) {
      final h = spineHadiths[i];
      var idInBook = _asInt(h['idInBook']);
      if (idInBook == null) {
        idInBook = i + 1;
        h['idInBook'] = idInBook;
      }
      byIdInBook.putIfAbsent(idInBook, () => h);
    }

    // Master hadith shells from spine.
    final masters = <Map<String, dynamic>>[];
    for (final h in spineHadiths) {
      final idInBook = _asInt(h['idInBook'])!;
      final grades = _gradesFromSpine(h);
      final reference = _referenceFromSpine(h);
      final translations = <String, dynamic>{};
      final en = h['english'];
      if (en is Map &&
          ((en['text'] as String?)?.trim().isNotEmpty == true ||
              (en['narrator'] as String?)?.trim().isNotEmpty == true)) {
        translations['en'] = {
          'narrator': (en['narrator'] as String?) ?? '',
          'text': (en['text'] as String?) ?? '',
        };
      }
      masters.add({
        'id': h['id'],
        'idInBook': idInBook,
        'chapterId': h['chapterId'] ?? 0,
        'bookId': book.id,
        'arabic': (h['arabic'] as String?) ?? '',
        'translations': translations,
        'grades': grades,
        'reference': reference,
      });
    }
    final masterByInBook = <int, Map<String, dynamic>>{
      for (final m in masters) m['idInBook'] as int: m,
    };

    final sources = <String>{'ahmedbaset', 'muallimai'};
    final languagesPresent = <String>{'ar'};
    if (masters.any((m) =>
        (m['translations'] as Map).containsKey('en'))) {
      languagesPresent.add('en');
    }

    // Fawaz editions for this book.
    if (book.fawazKey != null) {
      sources.add('fawaz');
      final editionFiles = Directory(
        '${db.path}${Platform.pathSeparator}editions${Platform.pathSeparator}files',
      );
      final fk = book.fawazKey!;
      final available = editionFiles
          .listSync()
          .whereType<File>()
          .map((f) => f.uri.pathSegments.last)
          .where((n) {
            if (!n.endsWith('.min.json')) return false;
            final stem = n.substring(0, n.length - '.min.json'.length);
            final dash = stem.indexOf('-');
            if (dash < 0) return false;
            final bookPart = stem.substring(dash + 1);
            return bookPart == fk || bookPart == '${fk}1';
          })
          .toList()
        ..sort();

      // Prefer primary lang-book; skip unknown suffixes except ara1.
      for (final name in available) {
        final stem = name.replaceAll('.min.json', ''); // e.g. eng-bukhari
        final dash = stem.indexOf('-');
        if (dash < 0) continue;
        final langPrefix = stem.substring(0, dash);
        final bookPart = stem.substring(dash + 1);
        final isAra1 = langPrefix == 'ara' && bookPart == '${fk}1';
        if (bookPart != fk && !isAra1) {
          notes.add(
            'Discarded (non-primary): `$stem` for book `${book.key}`',
          );
          continue;
        }
        final effectiveLang = isAra1 ? 'ara1' : langPrefix;
        final langDef = _langDefs[effectiveLang];
        if (langDef == null) {
          notes.add('Unknown lang prefix skipped: `$stem`');
          continue;
        }

        final fawaz = jsonDecode(
              File('${editionFiles.path}${Platform.pathSeparator}$name')
                  .readAsStringSync(),
            ) as Map<String, dynamic>;
        final rows = fawaz['hadiths'] as List? ?? const [];
        var matchHn = 0, matchAn = 0, miss = 0;

        for (final row in rows) {
          final r = row as Map;
          final hn = _asInt(r['hadithnumber']);
          final an = _asInt(r['arabicnumber']);
          Map<String, dynamic>? master;
          if (hn != null && masterByInBook.containsKey(hn)) {
            master = masterByInBook[hn];
            matchHn++;
          } else if (an != null && masterByInBook.containsKey(an)) {
            master = masterByInBook[an];
            matchAn++;
          } else {
            miss++;
            continue;
          }

          // Grades: prefer non-empty fawaz grades[].
          final fg = r['grades'];
          if (fg is List && fg.isNotEmpty) {
            final existing = master!['grades'] as List;
            if (existing.isEmpty || fg.length >= existing.length) {
              master['grades'] = fg
                  .map((e) => Map<String, dynamic>.from(e as Map))
                  .toList();
            }
          }

          final text = (r['text'] as String?)?.trim() ?? '';
          if (text.isEmpty) continue;

          if (effectiveLang == 'ara') {
            // Keep AhmedBaset Arabic on master; optionally fill if empty.
            if ((master!['arabic'] as String?)?.trim().isEmpty == true) {
              master['arabic'] = text;
            }
          } else if (effectiveLang == 'ara1') {
            // Store undiacritized as a translation language option.
            (master!['translations'] as Map)['ar-undiacritized'] = {
              'narrator': '',
              'text': text,
            };
            languagesPresent.add('ar-undiacritized');
          } else if (effectiveLang == 'eng') {
            // Prefer AhmedBaset English; only fill if missing.
            final tr = master!['translations'] as Map;
            if (!tr.containsKey('en')) {
              tr['en'] = {'narrator': '', 'text': text};
              languagesPresent.add('en');
            }
          } else {
            final code = langDef.code;
            // Indonesian: fawaz preferred over sagad drafts.
            (master!['translations'] as Map)[code] = {
              'narrator': '',
              'text': text,
            };
            languagesPresent.add(code);
          }
        }

        report.writeln(
          '| ${book.key} | $effectiveLang | ${rows.length} | $matchHn | $matchAn | $miss | ${masters.length} |',
        );
      }
    }

    // Sagad Indonesian drafts for languages still missing id.
    final sagadRel = book.spineRel; // same relative path under by_locale/id/by_book
    final sagadFile = File(
      '${db.path}${Platform.pathSeparator}by_locale${Platform.pathSeparator}id'
      '${Platform.pathSeparator}by_book${Platform.pathSeparator}'
      '${sagadRel.replaceAll('/', Platform.pathSeparator)}',
    );
    var usedSagad = false;
    if (sagadFile.existsSync()) {
      final needInd = !languagesPresent.contains('id') || book.fawazKey == null;
      // Always backfill spine rows missing Indonesian when sagad has them;
      // prefer fawaz when already present on a hadith.
      final sagad =
          jsonDecode(sagadFile.readAsStringSync()) as Map<String, dynamic>;
      for (final row in sagad['hadiths'] as List? ?? const []) {
        final r = Map<String, dynamic>.from(row as Map);
        final idInBook = _asInt(r['idInBook']);
        if (idInBook == null) continue;
        final master = masterByInBook[idInBook];
        if (master == null) continue;
        final tr = master['translations'] as Map;
        if (tr.containsKey('id')) continue; // fawaz already filled
        final t = r['translation'];
        if (t is! Map) continue;
        final text = (t['text'] as String?)?.trim() ?? '';
        if (text.isEmpty) continue;
        tr['id'] = {
          'narrator': (t['narrator'] as String?) ?? '',
          'text': text,
          'status': 'draft',
        };
        languagesPresent.add('id');
        usedSagad = true;
      }
      if (usedSagad) {
        sources.add('sagad');
        if (needInd) {
          notes.add(
            'Indonesian for `${book.key}`: sagad draft (no/partial fawaz).',
          );
        } else {
          notes.add(
            'Indonesian for `${book.key}`: fawaz primary; sagad backfilled unmatched rows as draft.',
          );
        }
      }
    }

    // Write master by_book.
    final draftId = languagesPresent.contains('id') &&
        masters.any((m) {
          final t = (m['translations'] as Map)['id'];
          return t is Map && t['status'] == 'draft';
        });

    final masterMeta = <String, dynamic>{
      'bookId': book.id,
      'bookKey': book.key,
      'arabic': spineMeta['arabic'] ?? {'title': '', 'author': ''},
      'english': spineMeta['english'] ?? {'title': '', 'author': ''},
      'chapters': chapters,
      'languages': (languagesPresent.toList()..sort()),
      'sources': (sources.toList()..sort()),
      if (draftId) 'translationStatus': 'draft',
    };
    final masterDoc = {
      'metadata': masterMeta,
      'hadiths': masters,
    };
    _writeJson(
      File('${byBookDir.path}${Platform.pathSeparator}${book.key}.json'),
      masterDoc,
    );
    _writeJson(
      File('${byBookDir.path}${Platform.pathSeparator}${book.key}.min.json'),
      masterDoc,
      min: true,
    );

    // Emit per-language edition views.
    final engTitle =
        (spineMeta['english'] as Map?)?['title'] as String? ?? book.key;
    final engAuthor =
        (spineMeta['english'] as Map?)?['author'] as String? ?? '';
    final araTitle =
        (spineMeta['arabic'] as Map?)?['title'] as String? ?? '';
    final araAuthor =
        (spineMeta['arabic'] as Map?)?['author'] as String? ?? '';

    // Always emit ara + eng.
    final langEmitOrder = <String>[
      'ar',
      if (languagesPresent.contains('ar-undiacritized')) 'ar-undiacritized',
      'en',
      ...'bn,fr,id,ru,ta,tr,ur'
          .split(',')
          .where(languagesPresent.contains),
    ];

    for (final langCode in langEmitOrder) {
      if (langCode != 'ar' &&
          langCode != 'en' &&
          !languagesPresent.contains(langCode)) {
        continue;
      }
      // eng/ara always from spine even if translation empty.
      final langDef = _langDefs.values.firstWhere(
        (l) => l.code == langCode,
        orElse: () => _LangDef(langCode, langCode, langCode),
      );
      final editionId = '${langDef.filePrefix}-${book.key}';
      final features = <String>{
        'arabic',
        'chapters',
        'reference',
        'grades',
      };
      var hasTranslation = false;
      final editionHadiths = <Map<String, dynamic>>[];

      for (final m in masters) {
        final trMap = m['translations'] as Map;
        Map<String, dynamic>? translation;
        if (langCode == 'ar') {
          translation = null;
        } else if (langCode == 'ar-undiacritized') {
          final t = trMap['ar-undiacritized'];
          if (t is Map) {
            translation = {
              'narrator': t['narrator'] ?? '',
              'text': t['text'] ?? '',
            };
          }
        } else {
          final t = trMap[langCode];
          if (t is Map) {
            translation = {
              'narrator': t['narrator'] ?? '',
              'text': t['text'] ?? '',
              if (t['status'] != null) 'status': t['status'],
            };
            if ((translation['text'] as String).trim().isNotEmpty) {
              hasTranslation = true;
            }
          } else if (langCode == 'en') {
            translation = {'narrator': '', 'text': ''};
          } else {
            translation = {'narrator': '', 'text': ''};
          }
        }

        final grades = (m['grades'] as List?) ?? const [];

        String arabicText = (m['arabic'] as String?) ?? '';
        if (langCode == 'ar-undiacritized') {
          final t = trMap['ar-undiacritized'];
          if (t is Map && (t['text'] as String?)?.isNotEmpty == true) {
            arabicText = t['text'] as String;
          }
        }

        final out = <String, dynamic>{
          'id': m['id'],
          'idInBook': m['idInBook'],
          'chapterId': m['chapterId'],
          'bookId': book.id,
          'arabic': arabicText,
          'translation': translation,
          'grades': grades,
          'reference': m['reference'],
        };
        if (translation != null && translation['status'] == 'draft') {
          out['translationStatus'] = 'draft';
        }
        editionHadiths.add(out);
      }

      if (langCode != 'ar' && langCode != 'ar-undiacritized') {
        if (hasTranslation || langCode == 'en') features.add('translation');
      }
      // Edition-level draft only when Indonesian is entirely/mostly sagad
      // (no fawaz ind file for this book).
      final draftCount = editionHadiths
          .where((h) => h['translationStatus'] == 'draft')
          .length;
      final isDraftInd = langCode == 'id' &&
          draftCount > 0 &&
          draftCount >= (editionHadiths.length / 2).ceil();

      final editionMeta = <String, dynamic>{
        'bookId': book.id,
        'bookKey': book.key,
        'language': langCode,
        'arabic': {'title': araTitle, 'author': araAuthor},
        'translation': langCode == 'ar'
            ? null
            : {
                'title': '$engTitle (${langDef.name})',
                'author': langCode == 'en' ? engAuthor : 'Various',
                'language': langCode,
                if (isDraftInd) 'translationStatus': 'draft',
              },
        'chapters': chapters,
        if (isDraftInd) 'translationStatus': 'draft',
      };

      final editionDoc = {
        'metadata': editionMeta,
        'hadiths': editionHadiths,
      };
      _writeJson(
        File('${filesDir.path}${Platform.pathSeparator}$editionId.json'),
        editionDoc,
      );
      _writeJson(
        File('${filesDir.path}${Platform.pathSeparator}$editionId.min.json'),
        editionDoc,
        min: true,
      );

      catalogEditions.add({
        'id': editionId,
        'bookKey': book.key,
        'bookId': book.id,
        'language': langCode,
        'languageName': langDef.name,
        'name': langCode == 'ar'
            ? '$engTitle (Arabic)'
            : '$engTitle (${langDef.name})',
        'hadithCount': editionHadiths.length,
        'features': (features.toList()..sort()),
        'path': 'files/$editionId.json',
        'sources': (sources.toList()..sort()),
        if (isDraftInd) 'translationStatus': 'draft',
      });

      matrix.putIfAbsent(book.key, () => <String>{}).add(langCode);
    }
  }

  final catalog = {
    'schemaVersion': _schemaVersion,
    'editions': catalogEditions,
  };
  _writeJson(
    File('${unified.path}${Platform.pathSeparator}catalog.json'),
    catalog,
  );
  _writeJson(
    File('${unified.path}${Platform.pathSeparator}catalog.min.json'),
    catalog,
    min: true,
  );

  report
    ..writeln()
    ..writeln('## Notes')
    ..writeln();
  for (final n in notes) {
    report.writeln('- $n');
  }
  report
    ..writeln()
    ..writeln('## Language × book matrix')
    ..writeln()
    ..writeln('| Book | Languages |')
    ..writeln('|---|---|');
  for (final book in _books) {
    final langs = matrix[book.key];
    if (langs == null) continue;
    report.writeln(
      '| ${book.key} | ${(langs.toList()..sort()).join(', ')} |',
    );
  }
  report
    ..writeln()
    ..writeln('## Edition count')
    ..writeln()
    ..writeln('Total editions: ${catalogEditions.length}');

  File('${unified.path}${Platform.pathSeparator}REPORT.md')
      .writeAsStringSync(report.toString());

  stdout.writeln(
    'Done. ${catalogEditions.length} editions → ${unified.path}',
  );
}

List<Map<String, dynamic>> _normalizeChapters(List raw) {
  return raw.map((c) {
    final m = Map<String, dynamic>.from(c as Map);
    return {
      'id': m['id'],
      'arabic': m['arabic'] ?? '',
      'english': m['english'] ?? '',
    };
  }).toList();
}

List<Map<String, dynamic>> _gradesFromSpine(Map<String, dynamic> h) {
  final g = h['grade'];
  if (g == null) return [];
  if (g is List) {
    return g.map((e) => Map<String, dynamic>.from(e as Map)).toList();
  }
  if (g is String && g.trim().isNotEmpty) {
    return [_parseGradeString(g.trim())];
  }
  return [];
}

Map<String, dynamic> _parseGradeString(String raw) {
  // e.g. "Sahih (Darussalam)" → name Darussalam, grade Sahih
  final m = RegExp(r'^(.*?)\s*\(([^)]+)\)\s*$').firstMatch(raw);
  if (m != null) {
    return {
      'name': m.group(2)!.trim(),
      'grade': m.group(1)!.trim(),
    };
  }
  return {'name': 'muallimai', 'grade': raw};
}

Map<String, dynamic>? _referenceFromSpine(Map<String, dynamic> h) {
  final r = h['reference'];
  if (r is Map) {
    return {
      if (r['text'] != null) 'text': r['text'],
      if (r['url'] != null) 'url': r['url'],
    };
  }
  return null;
}

int? _asInt(dynamic v) {
  if (v == null) return null;
  if (v is int) return v;
  if (v is double) return v.floor();
  if (v is num) return v.toInt();
  if (v is String) return int.tryParse(v);
  return null;
}

void _writeJson(File file, Object doc, {bool min = false}) {
  file.writeAsStringSync('${(min ? _min : _pretty).convert(doc)}\n');
}

class _BookDef {
  const _BookDef(this.key, this.id, this.spineRel, {this.fawazKey});
  final String key;
  final int id;
  final String spineRel;
  final String? fawazKey;
}

class _LangDef {
  const _LangDef(this.code, this.name, this.filePrefix);
  final String code;
  final String name;
  final String filePrefix;
}
