import 'dart:convert';
import 'dart:io';
import 'arabic_match.dart';

/// STAGE: verification/report tool, repeatable.
///
/// Answers, per book, with actual verified per-citation correspondence (not
/// aggregate totals eyeballed against each other): exactly how does amrayn's
/// citation numbering relate to fawaz's `hadithnumber` numbering? For every
/// amrayn citation matched to a fawaz row (via `arabic_match.dart`'s content
/// matching, not by number), records:
/// - how many DISTINCT fawaz rows amrayn's citations collectively land on,
///   vs fawaz's own total row count and distinct-hadithnumber count (catches
///   duplicate hadithnumber values inside fawaz's own file)
/// - the actual distribution of "how many amrayn citations point to the
///   same fawaz row" (1:1, 2:1, 3:1, ...) -- this is the real, checked
///   answer to "does amrayn split repeated narrations under one fawaz
///   citation into multiple lettered entries", not an assumption
/// - which fawaz rows have ZERO amrayn citations pointing to them (fawaz-
///   only content, from amrayn's perspective) and vice versa (amrayn
///   citations with no fawaz match at all -- already covered by
///   content_match_amrayn_vs_known.dart, cross-referenced here)
///
/// OUTPUT: NUMBERING_RELATIONSHIP_MAP.md at the repo root -- a permanent,
/// documented record of the verified counting relationship per book, so
/// nobody (including future sessions) has to re-derive "why do these two
/// sources report different totals for the same book" from scratch again.
void main() {
  const books = ['bukhari', 'muslim', 'nasai', 'abudawud', 'tirmidhi', 'ibnmajah', 'malik'];
  final buf = StringBuffer();
  buf.writeln('# amrayn <-> fawaz hadith-counting relationship, verified per citation\n');
  buf.writeln(
    'Generated by `tool/build_numbering_relationship_map.dart`. Different '
    'sources report different "total hadith count" for the same book -- '
    'this file records the ACTUAL, per-citation-verified reason why, not an '
    'assumption. Matches are by Arabic text content (`arabic_match.dart`), '
    'never by citation number, so this is checking a real correspondence, '
    'not circular reasoning from the numbers themselves.\n',
  );

  buf.writeln('## Summary table\n');
  buf.writeln('| Book | Amrayn total | Fawaz rows | Fawaz distinct hadithnumber | Distinct fawaz rows amrayn actually lands on | Fawaz rows with duplicate hadithnumber | Fawaz rows amrayn never matches |');
  buf.writeln('|---|---:|---:|---:|---:|---:|---:|');

  final bookDetails = <String, StringBuffer>{};

  for (final book in books) {
    final fawazFile = File('db/editions/files/ara-$book.min.json');
    final amraynFile = File('sources/amrayn.com/processed/$book.json');
    if (!fawazFile.existsSync() || !amraynFile.existsSync()) continue;

    final fawazData = jsonDecode(fawazFile.readAsStringSync()) as Map<String, dynamic>;
    final fawazHadiths = (fawazData['hadiths'] as List).cast<Map<String, dynamic>>();
    final fawazArabic = fawazHadiths.map((h) => (h['text'] as String?) ?? '').toList();
    final fawazNumbers = fawazHadiths.map((h) => (h['hadithnumber'] as num).toInt()).toList();

    final amraynData = jsonDecode(amraynFile.readAsStringSync()) as Map<String, dynamic>;
    final amraynHadiths = (amraynData['hadiths'] as List).cast<Map<String, dynamic>>();
    final amraynArabic = amraynHadiths.map((h) => (h['arabic'] as String?) ?? '').toList();
    final amraynKeys = amraynHadiths.map((h) => (h['citation'] as String?) ?? '${h['idInBook']}').toList();

    // Duplicate hadithnumber detection within fawaz's own file.
    final numberCounts = <int, int>{};
    for (final n in fawazNumbers) {
      numberCounts[n] = (numberCounts[n] ?? 0) + 1;
    }
    final duplicateRows = numberCounts.values.where((c) => c > 1).fold<int>(0, (a, c) => a + c);
    final distinctNumbers = numberCounts.length;

    // Content-match every amrayn citation to a fawaz row index.
    final result = matchToCanonical(
      oldArabic: amraynArabic,
      canonicalArabic: fawazArabic,
      oldLabels: amraynKeys,
    );

    // Count how many amrayn citations land on each fawaz row index.
    final landingCounts = <int, int>{}; // fawaz row index -> count of amrayn citations
    final unmatchedAmrayn = <String>[];
    for (var i = 0; i < result.length; i++) {
      final idx = result[i];
      if (idx == null) {
        unmatchedAmrayn.add(amraynKeys[i]);
        continue;
      }
      landingCounts[idx] = (landingCounts[idx] ?? 0) + 1;
    }

    final distinctRowsLanded = landingCounts.length;
    final fawazRowsNeverMatched = fawazHadiths.length - distinctRowsLanded;

    // Distribution of "how many amrayn citations point to the same fawaz row".
    final distribution = <int, int>{}; // N amrayn citations -> count of fawaz rows with exactly N
    for (final count in landingCounts.values) {
      distribution[count] = (distribution[count] ?? 0) + 1;
    }

    buf.writeln(
      '| $book | ${amraynHadiths.length} | ${fawazHadiths.length} | $distinctNumbers | '
      '$distinctRowsLanded | $duplicateRows | $fawazRowsNeverMatched |',
    );

    final detail = StringBuffer();
    detail.writeln('## $book\n');
    detail.writeln('- amrayn citations: ${amraynHadiths.length}');
    detail.writeln('- fawaz physical rows: ${fawazHadiths.length} (${distinctNumbers} distinct `hadithnumber` values -- '
        '${fawazHadiths.length - distinctNumbers} rows share a `hadithnumber` with another row)');
    detail.writeln('- amrayn citations that content-matched to *some* fawaz row: ${result.length - unmatchedAmrayn.length} / ${result.length}');
    detail.writeln('- distinct fawaz rows those matches actually land on: $distinctRowsLanded '
        '(vs ${fawazHadiths.length} total fawaz rows -- $fawazRowsNeverMatched fawaz rows have zero amrayn citations pointing to them)');
    detail.writeln('\n**Verified landing distribution** (how many fawaz rows get exactly N amrayn citations pointing at them):\n');
    detail.writeln('| N amrayn citations -> 1 fawaz row | Count of fawaz rows |');
    detail.writeln('|---:|---:|');
    for (final n in (distribution.keys.toList()..sort())) {
      detail.writeln('| $n | ${distribution[n]} |');
    }
    final multiLanded = distribution.entries.where((e) => e.key > 1).fold<int>(0, (a, e) => a + e.value);
    final multiLandedAmraynEntries = distribution.entries.where((e) => e.key > 1).fold<int>(0, (a, e) => a + e.key * e.value);
    detail.writeln(
      '\n$multiLanded fawaz rows receive more than one amrayn citation each '
      '(${multiLandedAmraynEntries} amrayn citations total land there) -- this is the '
      'VERIFIED count of amrayn splitting a single fawaz-numbered narration into '
      'multiple citations, not an assumed one.',
    );
    bookDetails[book] = detail;
  }

  buf.writeln();
  for (final book in books) {
    if (bookDetails.containsKey(book)) buf.writeln(bookDetails[book].toString());
  }

  File('NUMBERING_RELATIONSHIP_MAP.md').writeAsStringSync(buf.toString());
  stdout.writeln('Wrote NUMBERING_RELATIONSHIP_MAP.md');
}
