// STAGE: verification/report tool, repeatable — cross-checks the amrayn.com
// "scrape 1.0" processed files (sources/amrayn.com/processed/*.json) against
// our own canonical spine (db/by_book/**/*.json), never modifies either
// side. Run any time either side changes to refresh the comparison.
//
// INPUT: sources/amrayn.com/processed/{book}.json (built by
// sources/amrayn.com/scripts/build_processed.dart) + db/unified/by_book/
// {bookKey}.json — this repo's own definition of canonical (see README.md's
// "Canonical data: db/unified/" section); `db/by_book/` is the OLDER,
// pre-multilingual-merge spine kept only for compatibility, not what this
// script means by "canonical". Both carry the same idInBook/reference/
// arabic fields for the books amrayn covers (unified only adds the
// `translations` map on top), so which one is used doesn't change the
// comparison numbers below — just which is honest to call canonical.
//
// OUTPUT: sources/amrayn.com/COMPARISON_REPORT.md — per-book counts of
// what each side HAS that the other is missing (existence gaps), plus each
// side's own "entry exists but content is blank" stub count, so a future
// gap-filling pass knows exactly where to look without re-deriving this.
//
// Matching key: amrayn's own `citation` field (or idInBook when there's no
// letter suffix) against a normalized citation pulled from canonical's
// `reference.text`/`reference.url` — both sides ultimately trace to the
// same sunnah.com-style numbering, so a matching key should represent the
// same hadith on both sides. Malik is the one exception: neither side's
// citation string round-trips cleanly through Malik's chapter-local URL
// scheme, so it's matched on (chapter, local#) directly from each side's
// own dedicated fields instead.
import 'dart:convert';
import 'dart:io';

class BookPaths {
  const BookPaths(this.amraynKey, this.canonicalPath, this.canonicalKey);
  final String amraynKey;
  final String canonicalPath;
  final String canonicalKey;
}

const List<BookPaths> books = [
  BookPaths('riyad_assalihin', 'db/unified/by_book/riyadussalihin.json', 'riyad_assalihin'),
  BookPaths('aladab_almufrad', 'db/unified/by_book/adab.json', 'aladab_almufrad'),
  BookPaths('shamail_muhammadiyah', 'db/unified/by_book/shamail.json', 'shamail_muhammadiyah'),
  BookPaths('bukhari', 'db/unified/by_book/bukhari.json', 'bukhari'),
  BookPaths('muslim', 'db/unified/by_book/muslim.json', 'muslim'),
  BookPaths('nasai', 'db/unified/by_book/nasai.json', 'nasai'),
  BookPaths('abudawud', 'db/unified/by_book/abudawud.json', 'abudawud'),
  BookPaths('tirmidhi', 'db/unified/by_book/tirmidhi.json', 'tirmidhi'),
  BookPaths('ibnmajah', 'db/unified/by_book/ibnmajah.json', 'ibnmajah'),
  BookPaths('malik', 'db/unified/by_book/malik.json', 'malik'), // special-cased below
  BookPaths('nawawi40', 'db/unified/by_book/nawawi40.json', 'nawawi40'),
  BookPaths('qudsi40', 'db/unified/by_book/qudsi40.json', 'qudsi40'),
  BookPaths('darimi', 'db/unified/by_book/darimi.json', 'darimi'),
];

/// Bonus books amrayn covers with no canonical counterpart in db/by_book at
/// all — not part of our 18-book library today, so "compare" doesn't apply;
/// reported separately as "amrayn-only, not yet in our library."
const List<String> bonusBooksNoCanonical = [
  'nasai_kubra_bonus',
  'mustadrak_alhakim_bonus',
];

const String processedDir = 'sources/amrayn.com/processed';

void main() {
  final buf = StringBuffer();
  buf.writeln('# amrayn.com vs. canonical (`db/unified/by_book/`) comparison');
  buf.writeln();
  buf.writeln(
    'Generated by `tool/compare_amrayn_vs_canonical.dart` — re-run any '
    'time either side changes. Read-only: neither side is modified by '
    'this script. "Canonical" here means `db/unified/by_book/`, per '
    'README.md\'s own "Canonical data: db/unified/" section — NOT '
    '`db/by_book/`, which the README explicitly demotes to a '
    'compatibility-only legacy layer. Both carry identical hadith content '
    'for every book compared below, so this distinction doesn\'t change '
    'any number here; it only matters for which path to point at next '
    'time.',
  );
  buf.writeln();
  buf.writeln(
    '"Missing" below always means EXISTENCE (the hadith isn\'t present '
    'on that side at all under any matching key), not a content quality '
    'judgement. "Content-blank" means the entry exists but its '
    'Arabic/English text is empty — a different, narrower kind of gap.',
  );
  buf.writeln();
  buf.writeln(
    '| Book | Canonical total | Canonical content-blank | Amrayn total | '
    'Matched (both) | Canonical-only (amrayn missing) | '
    'Amrayn-only (canonical missing) |',
  );
  buf.writeln('|---|---:|---:|---:|---:|---:|---:|');

  final notes = StringBuffer();

  for (final b in books) {
    final canonicalFile = File(b.canonicalPath);
    final amraynFile = File('$processedDir/${b.amraynKey}.json');
    if (!canonicalFile.existsSync() || !amraynFile.existsSync()) {
      buf.writeln('| ${b.canonicalKey} | — | — | — | — | — | — |');
      continue;
    }

    final canonical = jsonDecode(canonicalFile.readAsStringSync()) as Map<String, dynamic>;
    final canonicalHadiths = (canonical['hadiths'] as List).cast<Map<String, dynamic>>();

    final amrayn = jsonDecode(amraynFile.readAsStringSync()) as Map<String, dynamic>;
    final amraynHadiths = (amrayn['hadiths'] as List).cast<Map<String, dynamic>>();

    final Map<String, Map<String, dynamic>> canonicalByKey = {};
    var canonicalBlank = 0;
    var fallbackToIdInBook = 0;
    for (final h in canonicalHadiths) {
      final key = b.canonicalKey == 'malik'
          ? _malikCanonicalKey(h)
          : _canonicalKey(h);
      if (key != null) canonicalByKey[key] = h;
      if (_isCanonicalBlank(h)) canonicalBlank++;
      if (b.canonicalKey != 'malik' && _usedIdInBookFallback(h)) {
        fallbackToIdInBook++;
      }
    }

    final Map<String, Map<String, dynamic>> amraynByKey = {};
    for (final h in amraynHadiths) {
      final key = b.canonicalKey == 'malik'
          ? _malikAmraynKey(h)
          : ((h['citation'] as String?) ?? '${h['idInBook']}');
      if (key != null) amraynByKey[key] = h;
    }

    final canonicalKeys = canonicalByKey.keys.toSet();
    final amraynKeys = amraynByKey.keys.toSet();
    final matched = canonicalKeys.intersection(amraynKeys).length;
    final canonicalOnly = canonicalKeys.difference(amraynKeys);
    final amraynOnly = amraynKeys.difference(canonicalKeys);

    buf.writeln(
      '| ${b.canonicalKey} | ${canonicalHadiths.length} | $canonicalBlank | '
      '${amraynHadiths.length} | $matched | ${canonicalOnly.length} | '
      '${amraynOnly.length} |',
    );

    if (canonicalOnly.isNotEmpty || amraynOnly.isNotEmpty || canonicalBlank > 0) {
      notes.writeln('### ${b.canonicalKey}');
      if (canonicalOnly.isNotEmpty) {
        final sample = canonicalOnly.toList()..sort();
        notes.writeln(
          '- Canonical has ${canonicalOnly.length} hadith amrayn\'s scrape '
          'doesn\'t (amrayn dead-link/gap, or amrayn simply doesn\'t cover '
          'this range). Sample keys: '
          '${sample.take(15).join(', ')}${sample.length > 15 ? ', …' : ''}',
        );
      }
      if (amraynOnly.isNotEmpty) {
        final sample = amraynOnly.toList()..sort();
        notes.writeln(
          '- Amrayn has ${amraynOnly.length} hadith our canonical spine '
          'doesn\'t — candidates to recover FROM amrayn, but check the '
          'real original source first per policy. Sample keys: '
          '${sample.take(15).join(', ')}${sample.length > 15 ? ', …' : ''}',
        );
      }
      if (canonicalBlank > 0) {
        notes.writeln(
          '- $canonicalBlank canonical entries exist but carry no '
          'Arabic/English content (`noSourceContent`/blank) — amrayn\'s '
          'scrape may have real text for some of these even where the key '
          'itself matched (a matched key does not guarantee non-blank '
          'canonical content).',
        );
      }
      if (fallbackToIdInBook > 0) {
        final pct = (fallbackToIdInBook / canonicalHadiths.length * 100).round();
        notes.writeln(
          '- **Confidence caveat**: $fallbackToIdInBook of ${canonicalHadiths.length} '
          'canonical entries ($pct%) had no parseable citation text and were '
          'matched by `idInBook` alone instead of a real citation string — '
          'reliable only if canonical\'s `idInBook` for this book actually '
          'lines up with amrayn\'s own numbering (true for books that went '
          'through this repo\'s content-matching rebuild; unverified '
          'otherwise). Treat this book\'s matched/missing counts as '
          'lower-confidence in proportion to this percentage.',
        );
      }
      notes.writeln();
    }
  }

  buf.writeln();
  buf.writeln('## Amrayn-only bonus books (no canonical counterpart yet)');
  buf.writeln();
  buf.writeln('| Book | Amrayn total |');
  buf.writeln('|---|---:|');
  for (final key in bonusBooksNoCanonical) {
    final f = File('$processedDir/$key.json');
    if (!f.existsSync()) continue;
    final data = jsonDecode(f.readAsStringSync()) as Map<String, dynamic>;
    final count = (data['hadiths'] as List).length;
    buf.writeln('| $key | $count |');
  }

  buf.writeln();
  buf.writeln('## Per-book notes');
  buf.writeln();
  buf.write(notes.toString());

  File('sources/amrayn.com/COMPARISON_REPORT.md').writeAsStringSync(buf.toString());
  stdout.writeln('Wrote sources/amrayn.com/COMPARISON_REPORT.md');
}

final _leadingHadithNum = RegExp(r'^Hadith\s+(\d+[a-z]?)\b');
final _trailingCitation = RegExp(r'^\d+[a-z]?$');

/// Normalizes canonical's `reference.text` down to the same bare citation
/// string amrayn's own `citation` field already uses (e.g. "Sahih Muslim
/// 11b" -> "11b", "Sunan Abi Dawud 1" -> "1", "Hadith 1, 40 Hadith
/// an-Nawawi" -> "1" — this repo's forties books put the number FIRST, not
/// last, so the trailing-token heuristic alone mis-parses them).
///
/// Falls back to `idInBook` when there's no usable citation text at all —
/// some records (mostly ones fawaz's own content-matching pipeline
/// couldn't confidently place onto a real citation, e.g. large stretches of
/// Darimi, sourced from mhashim6 rather than sunnah.com numbering) only
/// carry a `reference.url` in fawaz's internal `urn/NNNNNNN` scheme, which
/// has no relationship to amrayn's citation numbering at all — `idInBook`
/// is the best available join key for those, same as it's amrayn's own
/// fallback when a hadith never got a lettered citation.
String? _canonicalKey(Map<String, dynamic> h) {
  final ref = h['reference'] as Map<String, dynamic>?;
  final text = ref?['text'] as String?;
  if (text != null && text.trim().isNotEmpty) {
    final trimmed = text.trim();
    final leading = _leadingHadithNum.firstMatch(trimmed);
    if (leading != null) return leading.group(1);
    final last = trimmed.split(RegExp(r'\s+')).last;
    if (_trailingCitation.hasMatch(last)) return last;
  }
  final idInBook = h['idInBook'];
  return idInBook == null ? null : '$idInBook';
}

/// True when [_canonicalKey] had to fall back to `idInBook` for [h] because
/// no parseable citation text was available — see [_canonicalKey]'s own doc
/// comment for what that implies about match confidence.
bool _usedIdInBookFallback(Map<String, dynamic> h) {
  final ref = h['reference'] as Map<String, dynamic>?;
  final text = ref?['text'] as String?;
  if (text == null || text.trim().isEmpty) return true;
  final trimmed = text.trim();
  if (_leadingHadithNum.hasMatch(trimmed)) return false;
  final last = trimmed.split(RegExp(r'\s+')).last;
  return !_trailingCitation.hasMatch(last);
}

/// Malik-specific: canonical carries chapter/local only inside
/// `reference.url` (".../malik/{chapter}/{local}") — no dedicated fields
/// like amrayn's own malikChapterNum/malikLocalHadithNum.
final _malikUrlPattern = RegExp(r'malik/(\d+)/(\d+)');
String? _malikCanonicalKey(Map<String, dynamic> h) {
  final url = (h['reference'] as Map<String, dynamic>?)?['url'] as String?;
  if (url == null) return null;
  final m = _malikUrlPattern.firstMatch(url);
  if (m == null) return null;
  return '${m.group(1)}/${m.group(2)}';
}

String? _malikAmraynKey(Map<String, dynamic> h) {
  final chapter = h['malikChapterNum'];
  final local = h['malikLocalHadithNum'];
  if (chapter == null || local == null) return null;
  return '$chapter/$local';
}

/// True when canonical explicitly flags no content, OR both Arabic and
/// English text are empty. Checks both shapes: the older `db/by_book/`
/// spine's flat `english.text`, and `db/unified/by_book/`'s
/// `translations.en.text` (the `noSourceContent` flag itself is a
/// known gap in `build_unified_editions.dart` — never copied from the
/// spine into the unified rows, per that script's own TODO — so the
/// empty-text fallback is what actually catches these in unified data).
bool _isCanonicalBlank(Map<String, dynamic> h) {
  if (h['noSourceContent'] == true) return true;
  final arabic = (h['arabic'] as String?) ?? '';
  final flatEnglish = ((h['english'] as Map<String, dynamic>?)?['text'] as String?) ?? '';
  final translations = h['translations'] as Map<String, dynamic>?;
  final unifiedEnglish = ((translations?['en'] as Map<String, dynamic>?)?['text'] as String?) ?? '';
  return arabic.trim().isEmpty && flatEnglish.trim().isEmpty && unifiedEnglish.trim().isEmpty;
}
