/// STAGE: verification/report tool, repeatable — the CONTENT-based follow-up
/// to `tool/compare_amrayn_vs_canonical.dart`'s citation-string comparison.
///
/// That script found e.g. 1,854 Muslim hadith amrayn has that our canonical
/// citation numbering doesn't. But amrayn's citations (sunnah.com-style,
/// lettered: `8a`/`8b`/`8d`) and fawaz's raw numbering (plain integer 1..N,
/// no letters at all — verified directly: `db/editions/files/ara-muslim.min.json`
/// has zero string-typed `hadithnumber` values) are fundamentally different
/// *counting schemes* for the same book. A citation-string mismatch does NOT
/// mean the actual hadith text is missing from fawaz — it might just be
/// filed under a different plain number. This script answers the real
/// question with content, not labels: reuses `tool/arabic_match.dart`'s
/// proven `matchToCanonical` (100.00% verified on Ahmad/Darimi in its own
/// doc comment) to check whether each amrayn hadith's actual Arabic text
/// already exists SOMEWHERE in a known source, regardless of what number
/// either side calls it.
///
/// Meant to be extended, not just run once: every time a new source is
/// added to the "known" list, re-run this to see whether it recovers real
/// content that fawaz/canonical didn't have — this is the reusable
/// "run the new source through the same comparison against everything
/// known so far" step.
///
/// INPUT: sources/amrayn.com/processed/{book}.json (amrayn's full hadith
/// set) + one or more "known" Arabic corpora per book (currently just
/// fawaz's raw `db/editions/files/ara-{book}.min.json`; add more `KnownSource`
/// entries here as new sources come in).
///
/// OUTPUT: sources/amrayn.com/CONTENT_MATCH_REPORT.md — per book, how many
/// of amrayn's hadith have their Arabic text already present in a known
/// source (and which one), vs. genuinely absent from every known source
/// (real candidates to still need amrayn, or a source not yet added).
///
/// Usage: `dart run tool/content_match_amrayn_vs_known.dart [bookKey ...]`
library;

import 'dart:convert';
import 'dart:io';

import 'arabic_match.dart';

/// One already-known Arabic corpus to check amrayn's hadith against, for one
/// book. Add more entries (new sources, or a second file for a book) as they
/// come in — each is checked independently so the report can say WHICH
/// source recovered a given hadith, not just "found somewhere".
class KnownSource {
  const KnownSource(this.label, this.path, this.textField);
  final String label;
  final String path;

  /// Dot-path to the Arabic text field within each record, e.g. `'text'`
  /// for fawaz's flat shape or `'arabic'` for this repo's own spine shape.
  final String textField;
}

/// bookKey (amrayn's processed/{bookKey}.json) -> known corpora to check.
/// Only books with at least one locally-available raw corpus are listed —
/// see sources/amrayn.com/CONTENT_MATCH_REPORT.md's own notes for books
/// (e.g. Darimi, sourced from mhashim6) whose original isn't cached locally
/// and would need fetching before this script can check them.
final Map<String, List<KnownSource>> knownSourcesByBook = {
  'muslim': [
    const KnownSource(
      'fawaz raw (ara-muslim.min.json)',
      'db/editions/files/ara-muslim.min.json',
      'text',
    ),
  ],
};

void main(List<String> args) {
  final targets = args.isEmpty ? knownSourcesByBook.keys.toList() : args;
  final buf = StringBuffer();
  buf.writeln('# amrayn.com content-match vs. every known source');
  buf.writeln();
  buf.writeln(
    'Generated by `tool/content_match_amrayn_vs_known.dart` — the '
    'content-based follow-up to COMPARISON_REPORT.md\'s citation-string '
    'comparison. Matches by actual Arabic text (via '
    '`tool/arabic_match.dart`\'s `matchToCanonical`), not by citation '
    'number, since different sources count hadith differently (fawaz: '
    'flat integers, no letters at all; amrayn/sunnah.com: lettered '
    'sub-citations grouping repeated narrations). Re-run this any time a '
    'new source is added to `knownSourcesByBook` in the script itself.',
  );
  buf.writeln();

  for (final book in targets) {
    final sources = knownSourcesByBook[book];
    if (sources == null) {
      buf.writeln('## $book\n\nNo locally-available known corpus configured '
          'for this book yet — see script comments.\n');
      continue;
    }
    _runBook(book, sources, buf);
  }

  File('sources/amrayn.com/CONTENT_MATCH_REPORT.md').writeAsStringSync(buf.toString());
  stdout.writeln('Wrote sources/amrayn.com/CONTENT_MATCH_REPORT.md');
}

void _runBook(String book, List<KnownSource> sources, StringBuffer buf) {
  final amraynFile = File('sources/amrayn.com/processed/$book.json');
  if (!amraynFile.existsSync()) {
    buf.writeln('## $book\n\nNo sources/amrayn.com/processed/$book.json — '
        'run build_processed.dart first.\n');
    return;
  }
  final amraynData = jsonDecode(amraynFile.readAsStringSync()) as Map<String, dynamic>;
  final amraynHadiths = (amraynData['hadiths'] as List).cast<Map<String, dynamic>>();

  // Load every known source's Arabic text array once.
  final sourceTexts = <String, List<String>>{};
  for (final s in sources) {
    final f = File(s.path);
    if (!f.existsSync()) {
      stdout.writeln('WARNING: ${s.path} missing, skipping ${s.label}');
      continue;
    }
    final data = jsonDecode(f.readAsStringSync()) as Map<String, dynamic>;
    final rows = (data['hadiths'] as List).cast<Map<String, dynamic>>();
    sourceTexts[s.label] = rows.map((r) => (r[s.textField] as String?) ?? '').toList();
  }

  final amraynArabic = amraynHadiths.map((h) => (h['arabic'] as String?) ?? '').toList();
  final amraynKeys = amraynHadiths
      .map((h) => (h['citation'] as String?) ?? '${h['idInBook']}')
      .toList();

  // foundIn[i] = label of the first known source whose content-match
  // succeeded for amrayn hadith i, or null if no known source matched.
  final foundIn = List<String?>.filled(amraynHadiths.length, null);
  final matchStatsPerSource = <String, MatchStats>{};

  for (final entry in sourceTexts.entries) {
    final stats = MatchStats();
    final result = matchToCanonical(
      oldArabic: amraynArabic,
      canonicalArabic: entry.value,
      oldLabels: amraynKeys,
      stats: stats,
    );
    matchStatsPerSource[entry.key] = stats;
    for (var i = 0; i < result.length; i++) {
      if (foundIn[i] == null && result[i] != null) foundIn[i] = entry.key;
    }
  }

  final foundCount = foundIn.where((f) => f != null).length;
  final missingCount = foundIn.length - foundCount;

  buf.writeln('## $book');
  buf.writeln();
  buf.writeln('Amrayn total: ${amraynHadiths.length}');
  buf.writeln();
  buf.writeln('| Known source | Anchor matches | Fuzzy matches | Unmatched |');
  buf.writeln('|---|---:|---:|---:|');
  for (final e in matchStatsPerSource.entries) {
    buf.writeln(
      '| ${e.key} | ${e.value.anchorMatches} | ${e.value.fuzzyMatches} | ${e.value.unmatched} |',
    );
  }
  buf.writeln();
  buf.writeln(
    '**Content found in at least one known source: $foundCount / '
    '${amraynHadiths.length}. Genuinely absent from every known source: '
    '$missingCount** — these are the real candidates left needing amrayn '
    '(or a source not yet added), not just a citation-numbering mismatch.',
  );
  buf.writeln();

  if (missingCount > 0) {
    final missingSamples = <String>[];
    for (var i = 0; i < foundIn.length && missingSamples.length < 20; i++) {
      if (foundIn[i] == null) missingSamples.add(amraynKeys[i]);
    }
    buf.writeln(
      'Sample citations genuinely absent from every known source: '
      '${missingSamples.join(', ')}${missingCount > missingSamples.length ? ', …' : ''}',
    );
    buf.writeln();
  }
}
